### ISSUE TITLE
Add action to close out data update issue if no response after 30 days

### ISSUE THREAD

**Issue by lukefretwell** [civichackingagency/scangov#180]
Add action to close out data update issue if no response after 30 days.

New file to add:

`.github/workflows/close-stale-issue-data-update.yml`

Not sure if this is correct code (or file naming is best):

```
name: Close Stale Issues with 'data update' Label

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Close stale issues
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          stale-issue-message: "This issue has been automatically closed due to inactivity for 30 days."
          stale-pr-message: ""
          days-before-close: 0
          only-labels: 'data update'
          exempt-issue-labels: ''
          exempt-pr-labels: ''
          operations-per-run: 50
```
